apiVersion: v1
name: mediationplatform-customer-consumer
description: MyProject Mediation Platform consuming customer events from companyRef by eBus
type: application
version: 0.0.1
appVersion: "0.0.1"
sources:
 - https://gitlab.tech.MyProject/cl-platform/event-driven/mediationplatform-customer-consumer