platform: uat
ingressUrl: https://dashboard.caas-cnp-apps-np.com.intraMyProject/#/replicationcontroller?namespace=0ko-cl-mptf-uat
namespace: 0ko-cl-mptf-uat
env: uat
image: "${DOCKER_SNAPSHOT_IMAGE}"
deploy:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 500Mi
pvc:
  storage: 500Mi